[system]
username = ""
password = ""
instance_lock = false

[keybind]
play_pause = "${SPACE}"
lower_volume = "${DOWN}"
raise_volume = "${UP}"
lower_volume_fine = "${LEFT}"
raise_volume_fine = "${RIGHT}"
favourite_song = "f"
restart_player = "r"
seek_to_end = "s"
toggle_terminal = "i"

[display]
romaji_first = true
separator = ", "

[rpc]
enable = true
default_placeholder = " ♪"
fallback = "fallback2"
use_fallback = true
use_artist = true
detail = "${title}"
state = "${artist}"
large_text = "${source} ${title}"
small_text = "${artist}"
show_time_left = true
show_small_image = true

[player]
volume_step = 10
restart_timeout = 20

[player.mpv_options]
ad = "vorbis"
cache = true
cache_secs = 20
cache_pause_initial = true
cache_pause_wait = 3
demuxer_lavf_linearize_timestamps = true
