[system]
username = ""
password = ""
instance_lock = false

[keybind]
play_pause = "${SPACE}"
lower_volume = "${DOWN}"
raise_volume = "${UP}"
lower_volume_fine = "${LEFT}"
raise_volume_fine = "${RIGHT}"
favourite_song = "f"
restart_player = "r"
seek_to_end = "s"

[display]
romaji_first = true
separator = ", "

[rpc]
enable_rpc = true
default_placeholder = " ♪"
use_fallback = true
fallback = "fallback2"
use_artist = true

[player]
volume_step = 10
restart_timeout = 20

[player.mpv_options]
ad = "vorbis"
cache = true
cache_secs = 20
cache_pause_initial = true
cache_pause_wait = 3
demuxer_lavf_linearize_timestamps = true
